### ISSUE TITLE
Support for alternate REPLs?

### ISSUE THREAD

**Issue by 00dani** [raine/replem#1]
Could support be added for choosing a REPL other than the default Node one - say, CoffeeScript's? I've looked over the source and I don't think it'd be _especially_ difficult to allow something like:

```
replem --repl coffee-script/repl ramda:R
```

to invoke a CoffeeScript REPL instead - replem would basically just need to fetch the `coffee-script` package the same way it fetches the other packages you request, and then require `coffee-script/repl` instead of the core Node module `repl`.

Thoughts?

**Comment by raine** [comment]
What do you think about the following:

```
$ npm install --prefix ~/.replem coffee-script
coffee-script@1.10.0 .replem/node_modules/coffee-script
$ replem --repl coffee-script/repl ramda
Installed into REPL context:
 - ramda@0.17.1 as ramda
> (num for num in [10..1])
Array [ 10, 9, 8, 7, 6, 5, 4, 3, 2, 1 ]
```

Basically what you suggested, but without installing the repl module automatically.

**Comment by raine** [comment]
I added `--repl` in `1.6.0`

**Comment by 00dani** [comment]
Cool, that works! I figured automatically installing would make some kind of sense since the other arguments to replem work that way, but this is fine too. :sunglasses:
