### ISSUE TITLE
--repl coffee-script/repl is not there

### ISSUE THREAD

**Issue by algesten** [raine/replem#2]
Looks like it needs downloading first?

```
sultana$ replem --repl coffee-script/repl fnuc:F
Installed into REPL context:
 - fnuc@1.1.0 as F
{ [Error: Cannot find module '/Users/martin/.replem/node_modules/coffee-script/repl'] code: 'MODULE_NOT_FOUND' }
```

**Comment by algesten** [comment]
```
sultana$ ls ~/.replem/node_modules/
fnuc/  ramda/
```

**Comment by raine** [comment]
Yes, I've mentioned it here https://github.com/raine/replem#custom-repl

I have considered making it install the repl argument as well but have not decided yet if it's worth the trouble.

**Comment by raine** [comment]
Looks like it's in the examples of `--help` so admittedly it's not a good thing that it breaks without a proper explanation.

**Comment by algesten** [comment]
yes. it was the help that i was going on. a simple doc change would be fine i think.
though generally i use `npm install -g coffee-script` ... perhaps replem should have a fallback on the global?

**Comment by raine** [comment]
That's a good idea, but it seems like there's no way to require global modules without knowing where they are in the system. I'm going to remove the repl example from `--help` to avoid confusion and also add link to README there.

Thanks @algesten
