### ISSUE TITLE
optional init code

### ISSUE THREAD

**Issue by algesten** [raine/replem#3]
This is a feature request. I don't mind trying out a pull request, if you think it's a good idea and tell me if/how you want it done.

Pretty much every repl-interaction I do, I start with something like:

```
> R = require 'ramda'
> {map, filter, ifElse } = R
```

replem solves a big chunk of the problem with `ramda:R` but that startup line.

Perhaps something like

```
$ replem --init "{map, filter, ifElse} = R" ramda:R
```

**Comment by raine** [comment]
Is there something you don't like about extending context with whole ramda?

```
$ replem ramda:R!
Installed into REPL context:
 - ramda@0.17.1 as R
> filter
[Function: f2]
```

**Comment by algesten** [comment]
omg :D
